services:
  - type: worker
    name: Nimsafni
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: HUGGINGFACE_TOKEN
        sync: false
